# Generated by Django 2.0.8 on 2018-11-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'ordering': ['-created_at']},
        ),
    ]
