# Generated by Django 2.0.8 on 2018-11-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181120_1722'),
        ('notifications', '0003_auto_20181120_2222'),
    ]

    operations = [
    ]
